#!/bin/bash -ex

function error() {
    echo "ERROR: $*" 1>&2
    exit
}

# variables
DATE=$(date '+%Y%m%d%H%m')
if test -z "${DOMAIN}"; then
    error "Specifying a domain is mandatory, use -e DOMAIN=example.org"
fi
if test -z "${PASSWORD}"; then
    if test -e /etc/openldap/password; then
        export PASSWORD="$(cat /etc/openldap/password)"
    else
	apt-get update > /dev/null
	apt-get install --force-yes pwgen > /dev/null
        export PASSWORD=$(pwgen 20 1)
	apt-get remove --purge pwgen > /dev/null
	echo "password: $PASSWORD"
        echo "$PASSWORD" > /etc/ldap/password
	chmod go= /etc/ldap/password
    fi
fi
export BASEDN="dc=${DOMAIN//./,dc=}"

# configure
[ -f /etc/service/openldap/run.config ] && source /etc/service/openldap/run.config

# restore if required
if test -e /var/restore/*data.ldif; then
    rm -r /var/lib/ldap/* || true
    slapadd -f /etc/ldap/slapd.conf -l /var/restore/*data.ldif 2> /dev/null
    mv /var/restore/*data.ldif /var/backups/${DATE}-restored-data.ldif
else
    # backup status quo
    if test -n "$(ls -A /var/lib/ldap)"; then
        # This line will fail if ldap isn't already running, so ignore the error
        slapcat -f /etc/ldap/slapd.conf -F /etc/ldap/slapd.d > /var/backups/${DATE}-startup-data.ldif || true
    fi
fi

# add custom schemas
if test -e "${CUSTOM_SCHEMAS}"; then
    echo "add custom schemas";
    find "${CUSTOM_SCHEMAS}" -type f -name '*.schema' \
        -exec sh -c 'echo "include {}" >> /etc/ldap/slapd.conf' +
fi

function runInitScript {

    echo "wait server for initializing"
    until ldapwhoami -D "cn=admin,${BASEDN}" -w "${PASSWORD}"; do
        sleep 1
    done

    echo "run initialization script"
    ldapmodify -a -c -D "cn=admin,${BASEDN}" -w "${PASSWORD}" -f "${INIT_SCRIPT}"
}

if test -e "${INIT_SCRIPT}"; then
    runInitScript &
fi

# run
mkdir -p /var/lib/openldap/run
chown -R ${USER}.${GROUP} /var/lib/ldap /etc/ldap /var/lib/openldap
chmod 700 /var/lib/ldap
exec /usr/sbin/slapd -u $USER -g $GROUP -d ${DEBUG} -h "ldap:///${SSL_HOSTS}" -f /etc/ldap/slapd.conf -F /etc/ldap/slapd.d 2>&1 >> /var/log/openldap/current
