version: "3"
services:
  web:
    image: clonm/openldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    networks:
        server3:
          ipv4_address: '172.25.1.8'
    volumes:
    - ./var/lib/ldap:/var/lib/ldap
    # - ./etc/ldap:/etc/ldap

    environment:
      DOMAIN: cloyne.org
      PASSWORD: 1234567890
      DEBUG: 10

networks:
  server3:
    driver: bridge
    ipam:
      config:
        - subnet: '172.25.1.0/24'


